export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const START_LOADING = 'START_LOADING';
export const DONE_LOADING = 'DONE_LOADING';

export const CHANGE_FILES = 'CHANGE_FILES';
export const CHANGE_DIRECTORY = 'CHANGE_DIRECTORY';
export const SET_PATH = 'SET_PATH';

export const ADDFILE_MODAL_OPEN = 'ADDFILE_MODAL_OPEN';
export const ADDFILE_MODAL_CLOSE = 'ADDFILE_MODAL_CLOSE';
export const ADD_FILE = 'ADD_FILE';
