export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const START_LOADING = 'START_LOADING';
export const DONE_LOADING = 'DONE_LOADING';

export const CHANGE_FILES = 'CHANGE_FILES';
